### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ahmetozalp** [VctrySam/SnapChat#9]
/Users/apple/Desktop/Photo/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: xcodebuild process exited with code 65
    at ChildProcess.<anonymous> (/Users/apple/Desktop/Photo/node_modules/react-native/local-cli/runIOS/runIOS.js:102:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:504:12)

**Comment by shubs** [comment]
I have the same one

**Comment by diephil** [comment]
same here :'(

**Comment by vrishank97** [comment]
ditto

**Comment by ledbetterljoshua** [comment]
Ditto. @VctrySam are you able to replicate this?

**Comment by siliconprime-thangcao** [comment]
me too this issue :(

**Comment by reganjelcic** [comment]
SAM OKORO IS A SCAMMER!!!! READ ABOUT HIM HERE http://www.vctrysam.com/
